spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb_dev
    username: authuser_dev
    password: authpassword_dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
