spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb_prod
    username: authuser_prod
    password: authpassword_prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
