spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb_prod
    username: useruser_prod
    password: userpassword_prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
