spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb_dev
    username: useruser_dev
    password: userpassword_dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
