spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: useruser
    password: userpassword
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
