server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo
          fail-on-error: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
